{% set name = "anaconda-cloud-cli" %}
{% set snake_name = name | replace("-", "_") %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ snake_name }}-{{ version }}.tar.gz
  sha256: b72b3008ea3b57f11dbe5535db9c016f594ac378fb15dea3b52874ad279fcd62

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling >=1.20.0
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python

test:
  # No imports because it's an empty package
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.util import find_spec; assert not bool(find_spec(\"anaconda_cloud_cli\"))"

about:
  summary: The Anaconda Cloud CLI
  description: The Anaconda Cloud CLI
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://pypi.org/project/anaconda-cloud-cli/
  dev_url: https://github.com/anaconda/anaconda-cloud-tools/tree/main/libs/anaconda-cloud-cli

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
